# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import PubSub_pb2 as PubSub__pb2


class PubSubServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PubSubStream = channel.unary_stream(
                '/grpc.PubSubServer/PubSubStream',
                request_serializer=PubSub__pb2.Empty.SerializeToString,
                response_deserializer=PubSub__pb2.Note.FromString,
                )
        self.SendNote = channel.unary_unary(
                '/grpc.PubSubServer/SendNote',
                request_serializer=PubSub__pb2.Note.SerializeToString,
                response_deserializer=PubSub__pb2.Empty.FromString,
                )


class PubSubServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PubSubStream(self, request, context):
        """This bi-directional stream makes it possible to send and receive Notes between 2 persons
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendNote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PubSubServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PubSubStream': grpc.unary_stream_rpc_method_handler(
                    servicer.PubSubStream,
                    request_deserializer=PubSub__pb2.Empty.FromString,
                    response_serializer=PubSub__pb2.Note.SerializeToString,
            ),
            'SendNote': grpc.unary_unary_rpc_method_handler(
                    servicer.SendNote,
                    request_deserializer=PubSub__pb2.Note.FromString,
                    response_serializer=PubSub__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.PubSubServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PubSubServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PubSubStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc.PubSubServer/PubSubStream',
            PubSub__pb2.Empty.SerializeToString,
            PubSub__pb2.Note.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendNote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.PubSubServer/SendNote',
            PubSub__pb2.Note.SerializeToString,
            PubSub__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
